### ISSUE TITLE
Help on German translation

### ISSUE THREAD

**Issue by copiis** [fellownet/chronograph#1]
Hi, i can help on the german translation.
Which files did I have to edit?

**Comment by fellownet** [comment]
Awesome, as I haven't had the time to move all translations to transifex yet :)

I've put all the translation files in the locales folder, but the most work will be the app.json file, as that one contains the descriptions and hints for the flow cards.

**Comment by copiis** [comment]
Done...

**Comment by copiis** [comment]
Hello Bob, what does 

> Transition

 actually mean and what does this function do in the app? I don't think the German translation of this word is quite appropriate.

**Comment by fellownet** [comment]
It is a transition from one value to another over a certain time span. I'm using it myself to gradually lower the brightness of the lamps in my living room over a period of 5 minutes. This transition is then cancelled whenever I enter the area. Google Translate calls this an Ubergang? ;) Feel free to change it to whatever you seem fit using a merge request.
