### ISSUE TITLE
Bug in Timer longer or shorter than card

### ISSUE THREAD

**Issue by wan01524** [fellownet/chronograph#5]
Hi Bob
Think I found a small issue with the above mentioned card.
In case you use the card (in AND section) but the timer is not started the flow generate an error (see screen dumps), I would expect it to handle it like the timer value was zero.
I use this card to e.g. prevent reload of the timer in case it has not reached a certain time value.

Regards Allan

![2019-10-20 (1)](https://user-images.githubusercontent.com/53705491/67218066-06b57280-f426-11e9-9c7a-62716110153e.png)
![2019-10-20](https://user-images.githubusercontent.com/53705491/67218068-07e69f80-f426-11e9-9090-68d9cae76f59.png)

**Comment by fellownet** [comment]
The error is correct in saying that a timer is not running, so this is not actually a bug. You can use the "Timer is running" card to check if a timer is actually running, so you could create something like "if a timer is not running, or timer is shorter than...".

**Comment by wan01524** [comment]
I understand that, but this is not very ideal as you then will have to add additional flows or multiple conditions in the AND section just for preventing a timer to restart. If you look in my flow “Bevæg dag(c)....” I will have to create another flow as I will need four OR conditions which is not possible in the AND section.
