### ISSUE TITLE
Transition Bug

### ISSUE THREAD

**Issue by dirkg173** [fellownet/chronograph#6]
Hello,

I may have found a bug.
I wanted to create a transition for a Hue lamp (which makes little sense, cause you can create transitions directly with the Hue app...).
I entered the value 0.57 in the "To" field and wanted to confirm this. But I couldn't do that because the check mark was grayed out.
With the values 0.55 and 0.60 it is possible, with the values 0.56 - 0.59 it is not possible.

Is the problem known? Is it a bug?

Many greetings
Dirk

![42823C8F-C267-4A43-8C9C-8B1D709C1317](https://user-images.githubusercontent.com/40319629/75171107-6e106580-572b-11ea-847f-17dd42245844.jpeg)
![A7E987E6-7666-4B3E-9346-23DADD86E94F](https://user-images.githubusercontent.com/40319629/75171126-710b5600-572b-11ea-96eb-19f51794d300.jpeg)
![87F358F9-BC40-4BC4-B0D6-1F5320FC8913](https://user-images.githubusercontent.com/40319629/75171131-71a3ec80-572b-11ea-9fa9-edd519c390c3.jpeg)

**Comment by fellownet** [comment]
That's a very strange bug and probably not one that I can fix.

It's not the app that's doing the validation of the entered values, it's the Homey app itself. I'm just configuring the field to be a number, have a step value of 0.01 and a minimum of 0. The web based flow editor accepts the values just fine, so if necessary, you could resort to that.

**Comment by dirkg173** [comment]
Hi, I wrote to athom and told them about the problem.
But now Athom asks you to contact them directly. Enclosed you will find the correspondence.

Many thanks in advance!

[Bug in the Chronograph App caused by the Homey App.pdf](https://github.com/fellownet/chronograph/files/5347638/Bug.in.the.Chronograph.App.caused.by.the.Homey.App.pdf)
