### ISSUE TITLE
Feature Request: Stopwatch, timer, transition continues after restart of Homey

### ISSUE THREAD

**Issue by dirkg173** [fellownet/chronograph#9]
Is there a possibility that the stopwatch, a timer and/or transitions continues after a restart of Homey?
With the app "Countdown" by Ralf van Dooren this is possible (see post in the Homey Forum: https://community.athom.com/t/chronograph-adds-precise-timer-stopwatch-and-transition-functionality-to-homey/18214/82?u=fantross).

**Comment by fellownet** [comment]
This feature has been implemented in version 1.0.2:
* Timers and stopwatches are now persistent across application restarts and Homey reboots.
